(function(_ds){var window=this;var r3=function(a,b){b="translate3d("+b+"px,0px,0px)";_ds.am(a,q3(),b)},q3=_ds.pi(function(){return _ds.Ve&&9==_ds.qf?"-ms-transform":"transform"});var u3=function(a){a.h=s3(a,".devsite-top-logo-row-wrapper-wrapper");a.g=s3(a,".devsite-collapsible-section");a.o=s3(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.h}`);a.setAttribute("bottom-row--height",`${a.g}`);a.setAttribute("bottom-tabs--height",`${a.o}`);a.style.setProperty("--devsite-js-top-row--height",`${a.h}px`);a.style.setProperty("--devsite-js-bottom-row--height",`${a.g}px`);a.style.setProperty("--devsite-js-bottom-tabs--height",`${a.o}px`);t3(a)},t3=function(a){const b=
a.querySelector(".devsite-collapsible-section");a.offset>=a.g&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.g-a.o&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.oa&&(_ds.am(b,"transform",`translate3d(0, -${a.offset}px, 0)`),v3(a),a.oa=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.v()}px`)},w3=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),
d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.H(a.qa);a.ea&&window.cancelAnimationFrame(a.ea);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.Ci(b.offsetWidth,b.offsetHeight);b=new _ds.Ci(c.offsetWidth,c.offsetHeight);var f=_ds.tm(c),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.am(d,{opacity:1,width:`${b.width}px`,
height:`${b.height}px`});r3(c,a.hasAttribute("search-active")?0:e);_ds.Vl(a.qa,d,_ds.mg,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),r3(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.ea=window.requestAnimationFrame(()=>{c.setAttribute("transition","");var m="scale3d("+l+",1,1)";_ds.am(d,q3(),m);r3(c,k)})}},x3=async function(a,
b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");var e=null==a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.Ek(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled",
"")))}},z3=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.Ga;_ds.Aj(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>y3(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{y3(a)});a.eventHandler.listen(a,
"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},A3=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},v3=
function(a){0===a.g?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},y3=function(a){window.requestAnimationFrame(()=>a.va.Qa())},s3=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},B3=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=
a.attributes.item(c),b.setAttribute(d.name,d.value)},C3=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.gi(a,c,b))},D3=class extends _ds.D{constructor(){super(...arguments);this.eventHandler=new _ds.F;this.oa=-1;this.qa=new _ds.F;this.ea=0;this.ma=new MutationObserver(()=>u3(this));this.va=new _ds.Rl(()=>{u3(this);v3(this)},15);this.authUser=void 0;this.offset=this.o=this.g=this.h=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,
b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;t3(this);break;case "search-active":w3(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),x3(this,a)}}connectedCallback(){z3(this);A3(this);v3(this);u3(this);this.ma.observe(this,{childList:!0,subtree:!0});t3(this);
const a=_ds.E();this.authUser=_ds.ek(_ds.fk(a.href),"authuser")}disconnectedCallback(){_ds.H(this.eventHandler);this.ma.disconnect()}v(){return this.h+this.g-this.offset}ua(){return this.h+this.g}Xb(a){this.updated=!1;if(a){C3(this,a,".devsite-header-upper-tabs");C3(this,a,".devsite-collapsible-section");C3(this,a,".devsite-product-name-wrapper");C3(this,a,"devsite-language-selector");C3(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");
b&&c&&B3(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(B3(c,b),c=_ds.E(),c=_ds.ek(_ds.fk(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.gi(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.gi(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&
a&&(_ds.gj(this),this.appendChild(a));A3(this);y3(this)}};try{window.customElements.define("devsite-header",D3)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
